name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  bats:
    runs-on: macos-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install bats, php, and patchutils
        run: brew install bats-core php patchutils

      - name: Tests
        run: bin/test.sh
